#ifndef ESMACAT_PARAMETER_H
#define ESMACAT_PARAMETER_H

#include <iostream>
#include <string>
#include "esmacat_hardware_parameter.h"

#define TIMEOUT_WAITING_US_APP_ON 1000000
#define TIMEOUT_WAITING_US_ESMACAT_SETUP_DONE 1000000
#define TIMEOUT_WAITING_US_ECAT_SETUP_DONE 1000000
#define TIMEOUT_WAITING_US_DEFAULT 1000000
#define TIMEOUT_WAITING_NEXT_CYCLE_ECAT_MAIN_US 5000
#define MAX_NUMBER_OF_SEQUENTIAL_LOOPTIME_OVERFLOW   100
#define ALLOWED_LOOPTIME_OVERFLOW_NS   200000
#define MAX_NUMBER_OF_ETHERCAT_SLAVE   100
#define MAX_ECAT_INPUT_DATA_SIZE_BYTE 1000
#define MAX_ECAT_OUTPUT_DATA_SIZE_BYTE 1000

#define FLAG_TERMINATE_ECAT_IF_SLAVE_LOST TRUE
#define FLAG_TERMINATE_ECAT_WHEN_ESMACAT_APP_STOP TRUE

std::string get_ethercat_adapter_name();
unsigned long get_esmacat_default_loop_time_ns();

#endif // ESMACAT_PARAMETER_H
