#ifndef ESMACAT_HARDWARE_PARAMETER_H
#define ESMACAT_HARDWARE_PARAMETER_H

#define ESMACAT_DEFAULT_LOOP_TIME_NS 1000000L
#define ETHERCAT_ADAPTER_NAME "enp2s0"

#endif // ESMACAT_HARDWARE_PARAMETER_H
